## To modify by developer(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'nkt'  #to be modified, for instance daqmx then rename the module name:
# (pymodaq_plugins_template become pymodaq_plugins_daqmx for instance)

package-url = 'https://github.com/CRPP-CNRS-Metamaterials/pymodaq_plugins_nkt' #to modify
description = 'A PyMoDAQ plugin for NKT Photonics instruments'

author = 'Author Name'
author-email = 'Author email'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.3.6', 'pylablib>=1.4.3']

[features]  # defines the plugin features contained into this plugin
instruments = true  # true if plugin contains instrument classes (else false, notice the lowercase for toml files)
extensions = false  # true if plugins contains dashboard extensions
models = false  # true if plugins contains pid models or other models (optimisation...)
h5exporters = false  # true if plugin contains custom h5 file exporters
scanners = false  # true if plugin contains custom scan layout (daq_scan extensions)

